const SHEET_ID='1R4h8YtBFPDzD70DlNZQ88C7nJ9Gd9Yfd';
const API=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq`;
const $=s=>document.querySelector(s);
let staff=[];let trainingNames=[];let photoMap={};let selected=null;let requestNo=0;
const txt=(row,i)=>String(Array.isArray(row)?row?.[i]??'':row?.c?.[i]?.f??row?.c?.[i]?.v??'').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function query(sheet,headers){return new Promise((resolve,reject)=>{const cb=`__sheet_${Date.now()}_${Math.random().toString(36).slice(2)}`;const tag=document.createElement('script');let done=false;const finish=(err,value)=>{if(done)return;done=true;clearTimeout(timer);delete window[cb];tag.remove();err?reject(err):resolve(value)};window[cb]=value=>value.status==='ok'?finish(null,value.table):finish(new Error(value.errors?.[0]?.detailed_message||'Não foi possível ler a planilha.'));tag.onerror=()=>finish(new Error('Falha ao conectar com a planilha.'));const timer=setTimeout(()=>finish(new Error('Tempo de conexão esgotado.')),18000);tag.src=`${API}?tqx=${encodeURIComponent(`out:json;responseHandler:${cb}`)}&sheet=${encodeURIComponent(sheet)}&headers=${headers}`;document.head.append(tag)})}
function formatDate(value){if(!value)return '';let m=String(value).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?`${m[2].padStart(2,'0')}/${m[1].padStart(2,'0')}/${m[3]}`:String(value)}
function headerName(i){let s=String(window.__headers?.[i]||'').replace(/^\d+\s+/,'').trim();return s.replace(/^(?:DADOS GERAIS DO FUNCIONÁRIO|VALIDADE DO TREINAMENTO|AREAS RESTRITAS|AUTORIZADO A EXECUTAR|AUTORIZADO A OPERAR|AUTORIZADO A LIBERAR|EPI ESPECIAL|AUTORIZADO A PORTAR)\s*/i,'').trim()}
async function loadData(){const thisRequest=++requestNo;setStatus('Conectando à planilha…');$('#error').hidden=true;try{const [matrix,trainings,photos]=await Promise.all([query('Matriz',3),query('Treinamentos',1),fetch('assets/photos.json',{cache:'no-store'}).then(r=>r.ok?r.json():{}).catch(()=>({}))]);if(thisRequest!==requestNo)return;photoMap=photos;
  window.__headers=matrix.cols.map(c=>c.label||'');staff=matrix.rows.map(r=>({cells:r,id:txt(r,0)})).filter(x=>x.id);
  trainingNames=trainings.rows.map(r=>txt(r,0)).filter(Boolean);
  setStatus(`Planilha atualizada · ${staff.length} colaboradores`);if(selected){const updated=staff.find(x=>x.id===selected.id);if(updated){selected=updated;render(selected)}else clearResult()}
}catch(e){if(thisRequest!==requestNo)return;setStatus('Falha de conexão',true);$('#error').textContent=e.message;$('#error').hidden=false}}
function setStatus(s,error=false){const el=$('#source-status');el.textContent=s;el.dataset.state=error?'error':'ok'}
function field(label,value){return `<div class="field"><b>${esc(label)}</b><span>${esc(value||'—')}</span></div>`}
const icons={};
function readGroups(row){const groups=[['ÁREAS RESTRITAS',11,18],['AUTORIZADO A EXECUTAR',19,41],['AUTORIZADO A OPERAR',42,57],['AUTORIZADO A LIBERAR',58,66],['EPI ESPECIAL',67,69],['AUTORIZADO A PORTAR',70,71]];
 return groups.map(([title,start,end])=>({title,items:Array.from({length:end-start+1},(_,k)=>({name:headerName(start+k),date:formatDate(txt(row,start+k))})).filter(x=>x.name&&x.date)}));}
function render(item){const r=item.cells;const id=item.id;const name=txt(r,1);$('#employee-id').textContent=`REGISTRO ${id}`;$('#employee-name').textContent=name;$('#employee-role').textContent=`${txt(r,2)} · ${txt(r,4)}`;$('#empty').hidden=true;$('#error').hidden=true;$('#result').hidden=false;
 const stored=localStorage.getItem(`badge-photo-${id}`);const photoSrc=stored|| (photoMap[id]?`https://lh3.googleusercontent.com/d/${encodeURIComponent(photoMap[id])}=w1000`:null);const photo=photoSrc?`<img class="portrait" crossorigin="anonymous" alt="Foto de ${esc(name)}" src="${photoSrc}" onerror="this.classList.add('photo-failed')">`:`<div class="portrait photo-empty" aria-label="Foto não cadastrada"><span>FOTO</span></div>`;
 const restrictions=[11,12,13,14,15,16,17,18].map(i=>({name:headerName(i),date:formatDate(txt(r,i))})).filter(x=>x.name&&x.date);
 const restrict=restrictions.map(x=>`<li><span>${esc(x.name)}</span><b>${esc(x.date)}</b></li>`).join('')||'<li>Sem áreas restritas informadas</li>';
 $('#front-card').innerHTML=`<section class="front-panel"><div class="front-head"><img src="assets/enaex.png" alt="Enaex Brasil"><div class="seal">CONTROLE<br>INTERNO<br>REGISTRO<br>${esc(id)}</div><span class="version">VER. 1.1</span></div><div class="portrait-row">${photo}<div class="identity-fields">${field('NOME',name)}${field('FUNÇÃO',txt(r,2))}<div class="microgrid">${field('EMPRESA',txt(r,3))}${field('SETOR',txt(r,4))}</div></div></div><section class="restricted"><h4>ÁREAS RESTRITAS</h4><ul>${restrict}</ul></section><div class="validity">CONTROLE DE HABILITAÇÃO INTERNA<br>(C.H.I.)</div></section>`;
 const groups=readGroups(r);const training=groups.slice(1).filter(g=>g.items.length).map(g=>`<section class="group"><h4>${esc(g.title)}</h4><ul>${g.items.map(x=>`<li><span>${esc(x.name)}</span><b>${esc(x.date)}</b></li>`).join('')}</ul></section>`).join('')||'<div class="permission-empty">Sem habilitações informadas</div>';
 const license=[txt(r,8),txt(r,9)].filter(Boolean).join(' · ');const photoBack=stored?`<img src="${stored}" alt="">`:'';
 $('#back-card').innerHTML=`<section class="back-panel"><div class="back-head"><span>AUTORIZADO A EXECUTAR / OPERAR / LIBERAR</span><span>VALIDADE</span></div><div class="permissions">${training}</div><div class="authorization"><div class="back-head"><span>AUTORIZADO A PORTAR</span><span>SERIAL</span></div><div class="license">${esc(license||'T.I.MVV')}</div><div class="signature"></div><span>SSO MVVV</span></div><div class="back-footer">ENAEX BRASIL · US VALE VERDE</div></section>`;
 const back=$('#back-card');back.dataset.backPhoto=photoBack;$('#photo').value='';$('#pdf').disabled=false;$('#png').disabled=false;
}
function clearResult(){selected=null;$('#result').hidden=true;$('#empty').hidden=false;$('#empty').textContent='Digite o registro do colaborador.';$('#pdf').disabled=true;$('#png').disabled=true}
function search(){const id=$('#registro').value.trim();const found=staff.find(x=>x.id===id);if(!id)return;$('#error').hidden=true;if(!found){$('#error').textContent='Registro não encontrado.';$('#error').hidden=false;return}selected=found;render(found)}
const xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const wrapSvg=(value,max)=>{const out=[];let line='';for(const word of String(value||'—').split(/\s+/)){const next=line?line+' '+word:word;if(next.length>max&&line){out.push(line);line=word}else line=next}if(line)out.push(line);return out.slice(0,2)};
const st=(x,y,v,size=18,weight=400,color='#111',anchor='start')=>`<text x="${x}" y="${y}" font-family="Arial,Helvetica,sans-serif" font-size="${size}" font-weight="${weight}" fill="${color}" text-anchor="${anchor}">${xml(v)}</text>`;
async function badgeSvg(panel){const r=selected.cells,id=selected.id,logo=await (await fetch('assets/enaex.png')).blob(),photoSrc=localStorage.getItem(`badge-photo-${id}`)||(photoMap[id]?`https://lh3.googleusercontent.com/d/${encodeURIComponent(photoMap[id])}=w1000`:''),photo=photoSrc?await (await fetch(photoSrc)).blob():null;const data=async b=>b?await new Promise((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(f.result);f.onerror=reject;f.readAsDataURL(b)}):'';const [logoUrl,photoUrl]=await Promise.all([data(logo),data(photo)]);let s='<svg xmlns="http://www.w3.org/2000/svg" width="2400" height="4000" viewBox="0 0 600 1000"><rect x="2" y="2" width="596" height="996" fill="white" stroke="#222" stroke-width="2"/><rect x="12" y="12" width="576" height="976" fill="none" stroke="#444" stroke-dasharray="3 3"/>';
 if(panel.id==='front-card'){s+=`<image href="${logoUrl}" x="24" y="24" width="335" height="100" preserveAspectRatio="xMinYMid meet"/><circle cx="520" cy="72" r="43" fill="none" stroke="#08643f" stroke-width="4"/><circle cx="520" cy="72" r="36" fill="none" stroke="#08643f"/>${st(520,55,'CONTROLE',12,700,'#08643f','middle')}${st(520,72,'INTERNO',12,700,'#08643f','middle')}${st(520,89,'REG. '+id,11,700,'#08643f','middle')}${st(580,20,'VER. 1.1',10,600,'#222','end')}<rect x="22" y="140" width="222" height="330" fill="#e7e9ea" stroke="#555" stroke-dasharray="3 3"/>`;
  if(photoUrl)s+=`<svg x="24" y="142" width="218" height="326" viewBox="0 0 218 326" preserveAspectRatio="xMidYMid slice"><image href="${photoUrl}" width="218" height="326" preserveAspectRatio="xMidYMid slice"/></svg>`;else s+=st(133,315,'FOTO',18,600,'#8a8f92','middle');
  const addField=(x,y,w,h,label,value,fs=18)=>{let lines=wrapSvg(value,Math.floor(w/(fs*.56))),q=`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="white" stroke="#333" stroke-dasharray="3 3"/>${st(x+8,y+17,label,11,700)}`;lines.forEach((v,i)=>q+=st(x+8,y+41+i*21,v,fs));return q};
  s+=addField(252,140,326,86,'NOME',txt(r,1),17)+addField(252,232,326,86,'FUNÇÃO',txt(r,2),18)+addField(252,324,162,64,'EMPRESA',txt(r,3),17)+addField(416,324,162,64,'SETOR',txt(r,4),17)+'<rect x="22" y="490" width="556" height="372" fill="white" stroke="#333" stroke-dasharray="3 3"/><rect x="22" y="490" width="556" height="29" fill="#41484f"/>'+st(32,510,'ÁREAS RESTRITAS',16,700,'white');const items=[11,12,13,14,15,16,17,18].map(i=>[headerName(i),formatDate(txt(r,i))]).filter(a=>a[0]&&a[1]);items.forEach((a,i)=>{const y=548+i*34;s+=st(35,y,'▪',18,700)+st(55,y,a[0],15)+st(565,y,a[1],15,700,'#111','end')});s+='<rect x="22" y="882" width="556" height="96" fill="#08643f"/>'+st(300,924,'CONTROLE DE HABILITAÇÃO INTERNA',18,700,'white','middle')+st(300,950,'(C.H.I.)',17,700,'white','middle');
 }else{s+='<rect x="12" y="12" width="576" height="34" fill="#41484f"/>'+st(25,34,'AUTORIZADO A EXECUTAR',15,700,'white')+st(575,34,'VALIDADE',13,700,'white','end');const groups=readGroups(r).slice(1).filter(g=>g.items.length);const count=groups.reduce((n,g)=>n+g.items.length,0);const rowStep=Math.min(120,Math.max(34,650/Math.max(count,1)));let y=65;for(const g of groups){s+=st(23,y,g.title,14,700);y+=24;for(const a of g.items){s+=st(30,y,a.name,13)+st(575,y,a.date,13,600,'#111','end');y+=rowStep}y+=8}s+='<rect x="12" y="780" width="576" height="122" fill="white" stroke="#333" stroke-dasharray="3 3"/><rect x="12" y="780" width="576" height="32" fill="#41484f"/>'+st(25,802,'AUTORIZADO A PORTAR',14,700,'white')+st(575,802,'SERIAL',14,700,'white','end');const serial=[txt(r,8),txt(r,9)].filter(Boolean).join(' · ');s+=st(300,839,serial||'T.I.MVV',14,400,'#111','middle')+'<line x1="140" y1="870" x2="460" y2="870" stroke="#333" stroke-width="2"/>'+st(300,891,'SSO MVVV',13,400,'#111','middle')+'<rect x="12" y="914" width="576" height="64" fill="#08643f"/>'+st(300,953,'ENAEX BRASIL · US VALE VERDE',15,700,'white','middle')}
 return s+'</svg>'}
async function cardCanvas(panel){const svg=await badgeSvg(panel);const blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'});const url=URL.createObjectURL(blob);try{const im=new Image();im.src=url;await im.decode();const c=document.createElement('canvas');c.width=2400;c.height=4000;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);return c}finally{URL.revokeObjectURL(url)}}
async function toPngUrl(panel){const canvas=await cardCanvas(panel);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(URL.createObjectURL(b)):reject(new Error('Falha ao gerar imagem.')),'image/png'))}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function exportPng(){if(!selected)return;const urls=[];try{for(const [panel,side] of [[$('#front-card'),'frente'],[$('#back-card'),'verso']]){const u=await toPngUrl(panel);urls.push(u);download(u,`cracha-${selected.id}-${side}.png`)}}catch(e){$('#error').textContent=e.message;$('#error').hidden=false}}
function concatenate(parts){const size=parts.reduce((n,p)=>n+p.length,0);const out=new Uint8Array(size);let offset=0;for(const p of parts){out.set(p,offset);offset+=p.length}return out}
async function jpegBytes(panel){const canvas=await cardCanvas(panel);const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Falha ao preparar o PDF.')),'image/jpeg',.96));return new Uint8Array(await blob.arrayBuffer())}
function createPdf(images){const enc=new TextEncoder(),objects=[];objects[1]=enc.encode('<< /Type /Catalog /Pages 2 0 R >>');objects[2]=enc.encode('<< /Type /Pages /Kids [3 0 R 6 0 R] /Count 2 >>');const width=(54*72/25.4).toFixed(3),height=(86*72/25.4).toFixed(3);for(let page=0;page<2;page++){const p=3+page*3,c=p+1,im=p+2,jpeg=images[page],content=enc.encode(`q\n${width} 0 0 ${height} 0 0 cm\n/Im0 Do\nQ\n`);objects[p]=enc.encode(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /XObject << /Im0 ${im} 0 R >> >> /Contents ${c} 0 R >>`);objects[c]=concatenate([enc.encode(`<< /Length ${content.length} >>\nstream\n`),content,enc.encode('endstream')]);objects[im]=concatenate([enc.encode(`<< /Type /XObject /Subtype /Image /Width 2400 /Height 4000 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,enc.encode('\nendstream')])}const parts=[enc.encode('%PDF-1.4\n')],offsets=[0];let length=parts[0].length;for(let i=1;i<=8;i++){offsets[i]=length;const head=enc.encode(`${i} 0 obj\n`),tail=enc.encode('\nendobj\n');parts.push(head,objects[i],tail);length+=head.length+objects[i].length+tail.length}const xref=length;let table='xref\n0 9\n0000000000 65535 f \n';for(let i=1;i<=8;i++)table+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;table+=`trailer\n<< /Size 9 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(enc.encode(table));return new Blob([concatenate(parts)],{type:'application/pdf'})}
async function exportPdf(){if(!selected)return;try{const images=[];for(const panel of [$('#front-card'),$('#back-card')])images.push(await jpegBytes(panel));download(URL.createObjectURL(createPdf(images)),`cracha-${selected.id}.pdf`)}catch(e){$('#error').textContent=e.message;$('#error').hidden=false}}
$('#search').addEventListener('click',search);$('#registro').addEventListener('keydown',e=>{if(e.key==='Enter')search()});$('#refresh').addEventListener('click',loadData);$('#pdf').addEventListener('click',exportPdf);$('#png').addEventListener('click',exportPng);
$('#photo').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file||!selected)return;if(file.size>4*1024*1024){$('#error').textContent='A imagem deve ter no máximo 4 MB.';$('#error').hidden=false;return}const reader=new FileReader();reader.onload=()=>{try{localStorage.setItem(`badge-photo-${selected.id}`,reader.result);render(selected)}catch{$('#error').textContent='Não há espaço local disponível para salvar esta foto.';$('#error').hidden=false}};reader.readAsDataURL(file)});
loadData();
