const SHEET_ID='1R4h8YtBFPDzD70DlNZQ88C7nJ9Gd9Yfd';
const API=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq`;
const $=s=>document.querySelector(s);
let staff=[];let trainingNames=[];let photoMap={};let selected=null;let requestNo=0;
const txt=(row,i)=>String(Array.isArray(row)?row?.[i]??'':row?.c?.[i]?.f??row?.c?.[i]?.v??'').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function query(sheet,headers){return new Promise((resolve,reject)=>{const cb=`__sheet_${Date.now()}_${Math.random().toString(36).slice(2)}`;const tag=document.createElement('script');let done=false;const finish=(err,value)=>{if(done)return;done=true;clearTimeout(timer);delete window[cb];tag.remove();err?reject(err):resolve(value)};window[cb]=value=>value.status==='ok'?finish(null,value.table):finish(new Error(value.errors?.[0]?.detailed_message||'Não foi possível ler a planilha.'));tag.onerror=()=>finish(new Error('Falha ao conectar com a planilha.'));const timer=setTimeout(()=>finish(new Error('Tempo de conexão esgotado.')),18000);tag.src=`${API}?tqx=${encodeURIComponent(`out:json;responseHandler:${cb}`)}&sheet=${encodeURIComponent(sheet)}&headers=${headers}`;document.head.append(tag)})}
function formatDate(value){if(!value)return '';let m=String(value).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?`${m[2].padStart(2,'0')}/${m[1].padStart(2,'0')}/${m[3]}`:String(value)}
function headerName(i){let s=String(window.__headers?.[i]||'').replace(/^\d+\s+/,'').trim();return s.replace(/^(?:DADOS GERAIS DO FUNCIONÁRIO|VALIDADE DO TREINAMENTO|AREAS RESTRITAS|AUTORIZADO A EXECUTAR|AUTORIZADO A OPERAR|AUTORIZADO A LIBERAR|EPI ESPECIAL|AUTORIZADO A PORTAR)\s*/i,'').trim()}
async function loadData(){const thisRequest=++requestNo;setStatus('Conectando à planilha…');$('#error').hidden=true;try{const [matrix,trainings,photos]=await Promise.all([query('Matriz',3),query('Treinamentos',1),fetch('assets/photos.json',{cache:'no-store'}).then(r=>r.ok?r.json():{}).catch(()=>({}))]);if(thisRequest!==requestNo)return;photoMap=photos;
  window.__headers=matrix.cols.map(c=>c.label||'');staff=matrix.rows.map(r=>({cells:r,id:txt(r,0)})).filter(x=>x.id);
  trainingNames=trainings.rows.map(r=>txt(r,0)).filter(Boolean);
  setStatus(`Planilha atualizada · ${staff.length} colaboradores`);if(selected){const updated=staff.find(x=>x.id===selected.id);if(updated){selected=updated;render(selected)}else clearResult()}
}catch(e){if(thisRequest!==requestNo)return;setStatus('Falha de conexão',true);$('#error').textContent=e.message;$('#error').hidden=false}}
function setStatus(s,error=false){const el=$('#source-status');el.textContent=s;el.dataset.state=error?'error':'ok'}
function field(label,value){return `<div class="field"><b>${esc(label)}</b><span>${esc(value||'—')}</span></div>`}
const icons={};
function readGroups(row){const groups=[['ÁREAS RESTRITAS',11,18],['AUTORIZADO A EXECUTAR',19,41],['AUTORIZADO A OPERAR',42,57],['AUTORIZADO A LIBERAR',58,66],['EPI ESPECIAL',67,69],['AUTORIZADO A PORTAR',70,71]];
 return groups.map(([title,start,end])=>({title,items:Array.from({length:end-start+1},(_,k)=>({name:headerName(start+k),date:formatDate(txt(row,start+k))})).filter(x=>x.name&&x.date)}));}
function render(item){const r=item.cells;const id=item.id;const name=txt(r,1);$('#employee-id').textContent=`REGISTRO ${id}`;$('#employee-name').textContent=name;$('#employee-role').textContent=`${txt(r,2)} · ${txt(r,4)}`;$('#empty').hidden=true;$('#error').hidden=true;$('#result').hidden=false;
 const stored=localStorage.getItem(`badge-photo-${id}`);const photoSrc=stored|| (photoMap[id]?`https://lh3.googleusercontent.com/d/${encodeURIComponent(photoMap[id])}=w1000`:null);const photo=photoSrc?`<img class="portrait" crossorigin="anonymous" alt="Foto de ${esc(name)}" src="${photoSrc}" onerror="this.classList.add('photo-failed')">`:`<div class="portrait photo-empty" aria-label="Foto não cadastrada"><span>FOTO</span></div>`;
 const restrictions=[11,12,13,14,15,16,17,18].map(i=>({name:headerName(i),date:formatDate(txt(r,i))})).filter(x=>x.name&&x.date);
 const restrict=restrictions.map(x=>`<li><span>${esc(x.name)}</span><b>${esc(x.date)}</b></li>`).join('')||'<li>Sem áreas restritas informadas</li>';
 $('#front-card').innerHTML=`<section class="front-panel"><div class="front-head"><img src="assets/enaex.png" alt="Enaex Brasil"><div class="seal">CONTROLE<br>INTERNO<br>REGISTRO<br>${esc(id)}</div><span class="version">VER. 1.1</span></div><div class="portrait-row">${photo}<div class="identity-fields">${field('NOME',name)}${field('FUNÇÃO',txt(r,2))}<div class="microgrid">${field('EMPRESA',txt(r,3))}${field('SETOR',txt(r,4))}</div></div></div><section class="restricted"><h4>ÁREAS RESTRITAS</h4><ul>${restrict}</ul></section><div class="validity">CONTROLE DE HABILITAÇÃO INTERNA<br>(C.H.I.)</div></section>`;
 const groups=readGroups(r);const training=groups.slice(1).filter(g=>g.items.length).map(g=>`<section class="group"><h4>${esc(g.title)}</h4><ul>${g.items.map(x=>`<li><span>${esc(x.name)}</span><b>${esc(x.date)}</b></li>`).join('')}</ul></section>`).join('')||'<div class="permission-empty">Sem habilitações informadas</div>';
 const license=[txt(r,8),txt(r,9)].filter(Boolean).join(' · ');const photoBack=stored?`<img src="${stored}" alt="">`:'';
 $('#back-card').innerHTML=`<section class="back-panel"><div class="back-head"><span>AUTORIZADO A EXECUTAR / OPERAR / LIBERAR</span><span>VALIDADE</span></div><div class="permissions">${training}</div><div class="authorization"><div class="back-head"><span>AUTORIZADO A PORTAR</span><span>SERIAL</span></div><div class="license">${esc(license||'T.I.MVV')}</div><div class="signature"></div><span>SSO MVVV</span></div><div class="back-footer">ENAEX BRASIL · US VALE VERDE</div></section>`;
 const back=$('#back-card');back.dataset.backPhoto=photoBack;$('#photo').value='';$('#pdf').disabled=false;$('#png').disabled=false;
}
function clearResult(){selected=null;$('#result').hidden=true;$('#empty').hidden=false;$('#empty').textContent='Digite o registro do colaborador.';$('#pdf').disabled=true;$('#png').disabled=true}
function search(){const id=$('#registro').value.trim();const found=staff.find(x=>x.id===id);if(!id)return;$('#error').hidden=true;if(!found){$('#error').textContent='Registro não encontrado.';$('#error').hidden=false;return}selected=found;render(found)}
function photoFor(item){return localStorage.getItem(`badge-photo-${item.id}`)}
function buildSvg(panel,kind){const clone=panel.cloneNode(true);clone.style.width='600px';clone.style.height='1000px';clone.style.aspectRatio='';clone.classList.add('export-card');clone.querySelectorAll('img').forEach(im=>{im.crossOrigin='anonymous';im.src=new URL(im.getAttribute('src'),document.baseURI).href});const css=[...document.styleSheets].map(s=>{try{return[...s.cssRules].map(r=>r.cssText).join('')}catch{return''}}).join('');const markup=new XMLSerializer().serializeToString(clone);return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="2000" viewBox="0 0 600 1000"><foreignObject width="600" height="1000"><div xmlns="http://www.w3.org/1999/xhtml"><style>${css}</style>${markup}</div></foreignObject></svg>`}
async function toPngUrl(panel){const svg=buildSvg(panel);const blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'});const url=URL.createObjectURL(blob);try{const im=new Image();im.src=url;await im.decode();const c=document.createElement('canvas');c.width=2400;c.height=4000;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);return await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(URL.createObjectURL(b)):reject(new Error('Falha ao gerar imagem.')),'image/png'))}finally{URL.revokeObjectURL(url)}}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function exportPng(){if(!selected)return;const urls=[];try{for(const [panel,side] of [[$('#front-card'),'frente'],[$('#back-card'),'verso']]){const u=await toPngUrl(panel);urls.push(u);download(u,`cracha-${selected.id}-${side}.png`)}}catch(e){$('#error').textContent=e.message;$('#error').hidden=false}}
async function exportPdf(){if(!selected)return;try{if(!window.jspdf?.jsPDF)throw new Error('Não foi possível carregar o gerador de PDF.');const pdf=new window.jspdf.jsPDF({orientation:'portrait',unit:'mm',format:[54,86],compress:true});for(const [i,panel] of [$('#front-card'),$('#back-card')].entries()){if(i)pdf.addPage([54,86],'portrait');const u=await toPngUrl(panel);pdf.addImage(u,'PNG',0,0,54,86,undefined,'FAST');URL.revokeObjectURL(u)}pdf.save(`cracha-${selected.id}.pdf`)}catch(e){$('#error').textContent=e.message;$('#error').hidden=false}}
$('#search').addEventListener('click',search);$('#registro').addEventListener('keydown',e=>{if(e.key==='Enter')search()});$('#refresh').addEventListener('click',loadData);$('#pdf').addEventListener('click',exportPdf);$('#png').addEventListener('click',exportPng);
$('#photo').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file||!selected)return;if(file.size>4*1024*1024){$('#error').textContent='A imagem deve ter no máximo 4 MB.';$('#error').hidden=false;return}const reader=new FileReader();reader.onload=()=>{try{localStorage.setItem(`badge-photo-${selected.id}`,reader.result);render(selected)}catch{$('#error').textContent='Não há espaço local disponível para salvar esta foto.';$('#error').hidden=false}};reader.readAsDataURL(file)});
loadData();
